### ISSUE TITLE
Can't import project

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [square1-io/rich-text-android#3]
It shows me this issue:

![image](https://user-images.githubusercontent.com/5357526/36073889-633396da-0f40-11e8-8dc1-f771397c5772.png)

I had to remove/comment the entire "bintray" block, and the 2 lines of "properties" above it, and had to update the versions of everything.
Only then it imports well.
Please update the repo, and remove parts that shouldn't be there.

**Comment by robertoprato** [comment]
@AndroidDeveloperLB  i did a cleanup of the project files and removed the import issue.

**Comment by AndroidDeveloperLB** [comment]
ok seems to work fine now. Was hoping it had editing capabilities though. 
Thanks anyway.
